apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: __APP_NAME__-deploy
  namespace: __APP_NAME__
  labels:
    app: __APP_NAME__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: __APP_NAME__
  template:
    metadata:
      labels:
        app: __APP_NAME__
    spec:
      containers:
      - name: __APP_NAME__
        image: 260584439167.dkr.ecr.sa-east-1.amazonaws.com/__APP_NAME__:__TAG__
        env:
         - name: CONSUL_HOST
           valueFrom:
             configMapKeyRef:
               name: __APP_NAME__
               key: CONSUL_HOST
         - name: CONSUL_PORT
           valueFrom:
             configMapKeyRef:
               name: __APP_NAME__
               key: CONSUL_PORT
         - name: ADDITIONAL_OPTS
           valueFrom:
             configMapKeyRef:
               name: __APP_NAME__
               key: ADDITIONAL_OPTS
         - name: RABBITMQ_HOST
           valueFrom:
             configMapKeyRef:
               name: __APP_NAME__
               key: RABBITMQ_HOST
         - name: RABBITMQ_PORT
           valueFrom:
             configMapKeyRef:
               name: __APP_NAME__
               key: RABBITMQ_PORT
         - name: VAULT_SCHEME
           valueFrom:
             configMapKeyRef:
               name: __APP_NAME__
               key: VAULT_SCHEME
         - name: VAULT_HOST
           valueFrom:
             configMapKeyRef:
               name: __APP_NAME__
               key: VAULT_HOST
         - name: VAULT_SECURITY_TOKEN
           valueFrom:
             secretKeyRef:
               name: __APP_NAME__
               key: VAULT_SECURITY_TOKEN
        ports:
        - containerPort: 8080
        - containerPort: 5005
